// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nihpvxfocmdbzfnrqibu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5paHB2eGZvY21kYnpmbnJxaWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjI5NzAsImV4cCI6MjA2MDczODk3MH0.xk4iKzF2W-ymnByX6NnXEp8bIwkd0YcxJ58B0CUu8GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);